[project]
name = "tidalseis"
version = "0.1.0"
description = "Python implementation of stress model calculations based on tidally-controlled seismicity."
authors = [
    {name = "Z.M. Vig",email = "zvig@umd.edu"}
]
readme = "README"
requires-python = ">=3.13"
dependencies = [
    "numpy (>=2.4.4,<3.0.0)",
    "redpy (>=0.0.3,<0.0.4)",
    "obspy (>=1.5.0,<2.0.0)",
    "pydantic (>=2.13.4,<3.0.0)",
    "tqdm (>=4.67.3,<5.0.0)",
    "types-tqdm (>=4.67.3.20260518,<5.0.0.0)",
    "cartopy (>=0.25.0,<0.26.0)",
    "cmap (>=0.7.2,<0.8.0)",
    "pandas>=3.0.3",
    "click>=8.4.1",
    "pandas-stubs>=3.0.3.260530",
    "scipy-stubs>=1.17.1.5",
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[project.scripts]
download_network = "tidalseis.scripts.download_traces:main"
create_streams = "tidalseis.scripts.create_streams:main"
catalog = "tidalseis.scripts.create_catalog:main"
plot_tide_events = "tidalseis.scripts.plot_tidal_events:main"

[tool.hatch.build]
include = [
    "src/tidalseis/data"
]
