import re

CHANNEL_CODE_PATTERNS: dict[str, re.Pattern[str]] = {
    "ACE": re.compile(r"^ACE$"),
    "ACU": re.compile(r"^ACU$"),
    "BCI": re.compile(r"^BCI$"),
    "BH[ZNE]": re.compile(r"^BH[ZNE]$"),
    "BH[1-n]": re.compile(r"^BH\d+$"),
    "BJ[ZNE]": re.compile(r"^BJ[ZNE]$"),
    "BL[ZNE]": re.compile(r"^BL[ZNE]$"),
    "BN[ZNE]": re.compile(r"^BN[ZNE]$"),
    "BN[1-n]": re.compile(r"^BN\d+$"),
    "EH[ZNE]": re.compile(r"^EH[ZNE]$"),
    "EL[ZNE]": re.compile(r"^EL[ZNE]$"),
    "HD[IO]": re.compile(r"^HD[IO]$"),
    "HH[ZNE]": re.compile(r"^HH[ZNE]$"),
    "HJ[ZNE]": re.compile(r"^HJ[ZNE]$"),
    "HL[ZNE]": re.compile(r"^HL[ZNE]$"),
    "HL[1-n]": re.compile(r"^HL\d+$"),
    "HN[ZNE] or HN[123456]": re.compile(r"^HN[ZNE123456]$"),
    "LCE": re.compile(r"^LCE$"),
    "LCL": re.compile(r"^LCL$"),
    "LCQ": re.compile(r"^LCQ$"),
    "LD[IO]": re.compile(r"^LD[IO]$"),
    "LEB": re.compile(r"^LEB$"),
    "LEC": re.compile(r"^LEC$"),
    "LEP": re.compile(r"^LEP$"),
    "LH[ZNE]": re.compile(r"^LH[ZNE]$"),
    "LH[12]": re.compile(r"^LH[12]$"),
    "LII": re.compile(r"^LII$"),
    "LJ[ZNE]": re.compile(r"^LJ[ZNE]$"),
    "LKI": re.compile(r"^LKI$"),
    "LL[1-n]": re.compile(r"^LL\d+$"),
    "LN[ZNE] or LN[1-n]": re.compile(r"^LN[ZNE\d+]$"),
    "LOG": re.compile(r"^LOG$"),
    "LTW": re.compile(r"^LTW$"),
    "MH[ZNE]": re.compile(r"^MH[ZNE]$"),
    "OCF": re.compile(r"^OCF$"),
    "SH[ZNE]": re.compile(r"^SH[ZNE]$"),
    "UCD": re.compile(r"^UCD$"),
    "UCQ": re.compile(r"^UCQ$"),
    "UEP": re.compile(r"^UEP$"),
    "UF[1...n]": re.compile(r"^UF\d+$"),
    "UFC": re.compile(r"^UFC$"),
    "UK2": re.compile(r"^UK2$"),
    "UM[ZNE] or UM[UVW]": re.compile(r"^UM[ZNEUVW]$"),
    "VCE": re.compile(r"^VCE$"),
    "VCO": re.compile(r"^VCO$"),
    "VCQ": re.compile(r"^VCQ$"),
    "VD[IO]": re.compile(r"^VD[IO]$"),
    "VEA": re.compile(r"^VEA$"),
    "VEC": re.compile(r"^VEC$"),
    "VEP": re.compile(r"^VEP$"),
    "VFP": re.compile(r"^VFP$"),
    "VH[ZNE]": re.compile(r"^VH[ZNE]$"),
    "VK2": re.compile(r"^VK2$"),
    "VK[IO]": re.compile(r"^VK[IO]$"),
    "VM[ZNE] or VM[UVW]": re.compile(r"^VM[ZNEUVW]$"),
    "VN[ZNE]": re.compile(r"^VN[ZNE]$"),
}
